apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
spec:
  containers:
  - name: flask
    image: daxnii/flaskapp:v2.0.0
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: docker-pull-secret
